config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "dashboards#index"
  resources :candidates, :employees
  resources :reports, only: [:index]
  resources :interviews do 
    member do
      get 'feedback'
      post 'submit_feedback'
    end
  end
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
before_action :set_interview, only: [:show, :edit, :update, :destroy, :feedback, :submit_feedback, :edit_feedback]

  # GET /interviews
  # GET /interviews.json
  def index
    @interviews = Interview.all
  end

  # GET /interviews/1
  # GET /interviews/1.json
  def show
  end

  # GET /interviews/new
  def new
    @interview = Interview.new
  end

  # GET /interviews/1/edit
  def edit
  end

  # POST /interviews
  # POST /interviews.json
  def create
    @interview = Interview.new(interview_params)

    respond_to do |format|
      if @interview.save
        format.html { redirect_to @interview, notice: 'Interview was successfully created.' }
        format.json { render :show, status: :created, interview: @interview }
      else
        format.html { render :new }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1
  # PATCH/PUT /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to @interview, notice: 'interview was successfully updated.' }
        format.json { render :show, status: :ok, interview: @interview }
      else
        format.html { render :edit }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  def feedback
    @interview_skill_ratings = @interview.interview_skill_ratings.present? ? @interview.interview_skill_ratings : @interview.interview_skill_ratings.build 
  end

  def submit_feedback
    respond_to do |format|
      if @interview.update(interview_skill_rating_params)
        format.html { redirect_to @interview, notice: 'Interview Feedback was successfully created.' }
        format.json { render :show, status: :created, interview: @interview }
      else
        format.html { render :feedback }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_params
      params.require(:interview).permit(:candidate_id, :employee_id, :start_time, :end_time, :round, :remarks)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_skill_rating_params
      params.require(:interview).permit({ 
      interview_skill_ratings_attributes: [
          :core_skill_id, 
          :score,
          :id
        ] 
      })
    end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_feedback_form.html.erb
<%= form_for @interview, method: :post, url: submit_feedback_interview_path(@interview) do |f| -%>
<% if @interview.interview_skill_ratings.exists? %>

    <%= f.fields_for :interview_skill_ratings do |ff| %>
      <div class="field">
        <%= ff.label "#{ff.object.core_skill.name} Rating out of 5" %>
        <%= ff.hidden_field :core_skill_id, value: "#{ff.object.core_skill.id}" %>
        <%= ff.number_field :score, max: 5, min: 0, step: :any %>
      </div><br>
    <% end %>

<%else%>

  <% @interview.candidate.skills.each do |skill| %>
    <%= f.fields_for :interview_skill_ratings do |ff| %>
      <div class="field">
        <%= ff.label "#{skill.name} Rating out of 5" %>
        <%= ff.hidden_field :core_skill_id, value: "#{skill.id}" %>
        <%= ff.number_field :score, max: 5, min: 0, step: :any %>
      </div><br>
    <% end %>
  <% end %>
  
<%end%>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interviews/_form.html.erb
<%= form_with(model: interview, local: true) do |form| %>
  <% if interview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
      <% interview.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee %>
    <%= form.select :employee_id, Employee.pluck(:name, :id), prompt: "Please Select" %>
  </div><br>

  <div class="field">
    <%= form.label :candidate %>
    <%= form.select :candidate_id, Candidate.pluck(:name, :id), prompt: "Please Select" %>
  </div><br>

  <div class="field">
    <%= form.label :round %>
    <%= form.select :round, [1,2,3], prompt: "Please Select" %>
  </div><br>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div><br>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div><br>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interviews/edit.html.erb
<h1>Editing Interview</h1>

<%= render 'form', interview: @interview %>

<%= link_to 'Show', @interview %> |
<%= link_to 'Back', interviews_path %>

app/views/interviews/feedback.html.erb
<h1>Submit Feedback</h1>

<%= render 'feedback_form', interview_skill_ratings: @interview_skill_ratings %>

<%= link_to 'Back', interviews_path %>

app/views/interviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interviews</h1>

<table>
  <thead>
    <tr>
      <th>Candidate</th>
      <th>Employee</th>
      <th>Round</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Remark</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @interviews.each do |interview| %>
      <tr>
        <td><%= interview.candidate.try(:name) %></td>
        <td><%= interview.employee.try(:name) %></td>
        <td><%= interview.round %></td>
        <td><%= interview.start_time %></td>
        <td><%= interview.end_time %></td>
        <td><%= interview.remarks %></td>
        <td><%= link_to 'Show', interview %></td>
        <td><%= link_to 'Edit', edit_interview_path(interview) %></td>
        <td><%= link_to 'Feedback', feedback_interview_path(interview) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Schedule Interview', new_interview_path %>
<%= link_to 'Back', root_path %>

app/views/interviews/new.html.erb
<h1>Schedule Interview</h1>

<%= render 'form', interview: @interview %>

<%= link_to 'Back', interviews_path %>

app/views/interviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Candidate:</strong>
  <%= @interview.candidate.name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @interview.employee.name %>
</p>

<p>
  <strong>Round:</strong>
  <%= @interview.round %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @interview.start_time %>
</p>

<p>
  <strong>End Time:</strong>
  <%= @interview.end_time %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @interview.remarks %>
</p>

<%= link_to 'Edit', edit_interview_path(@interview) %> |
<%= link_to 'Back', interviews_path %>