config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "dashboards#index"
  resources :candidates, :employees
  resources :reports, only: [:index]
  resources :interviews do 
    member do
      get 'feedback'
      post 'submit_feedback'
    end
  end
end

app/models/candidate.rb
class Candidate < User
	validates_length_of :name, :maximum => 16
	validates :dob, :presence => true

	has_many :interviews, :dependent => :destroy
	
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, :email, :presence => true
	validates :experience, presence: true, :numericality => {:greater_than => 0}
	validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
	validate :core_skills_present

	has_many :user_core_skills, :as => :skillable, :dependent => :destroy, :class_name => "UserCoreSkill"
	has_many :skills, :through => :user_core_skills, :source => :core_skill 
	
	accepts_nested_attributes_for :user_core_skills

  private

  def core_skills_present
    errors.add(:skills, 'should be present.') unless skills.present?
  end

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
	before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, candidate: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name, :dob, :email, :experience, skill_ids: [])
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_with(model: candidate, local: true) do |form| %>
  <% if candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob, :start_year => 1950, :end_year => Date.current.year %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :experience %>
    <%= form.number_field :experience %>
  </div>

  <div class="field">
  <%= form.label :core_skill %>
  <%= form.collection_select :skill_ids, CoreSkill.all,:id,:name,{},{multiple: true, size: 10} %>
  </div>  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th>Email</th>
      <th>Experience</th>
      <th>Core Skills</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.dob %></td>
        <td><%= candidate.email %></td>
        <td><%= candidate.experience %></td>
        <td><%= get_user_skills(candidate) %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate', new_candidate_path %>
<%= link_to 'Dashboard', root_path %>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candidate.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @candidate.dob %>
</p>

<p>
  <strong>Email:</strong>
  <%= @candidate.email %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @candidate.experience %>
</p>

<p>
  <strong>Core Skills:</strong>
  <%= get_user_skills(@candidate) %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>